<?php
function e($value) { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); }
$is_edit = !empty($product);
$action = $is_edit ? site_url('products/edit/' . $product['id']) : site_url('products/create');
?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($heading) ?> | LavaLust</title><style>
:root{--ink:#18212b;--muted:#66727a;--paper:#f4f0e8;--white:#fffdf8;--accent:#d85b3f;--line:#d8d0c3}*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,var(--paper),#dce7e3);color:var(--ink);font:16px Georgia,serif}.wrap{width:min(700px,calc(100% - 32px));margin:auto;padding:48px 0}.back{color:var(--accent);font:700 14px Arial,sans-serif;text-decoration:none}h1{margin:26px 0 28px;font-size:clamp(2.2rem,6vw,4rem)}.panel{padding:32px;background:var(--white);border:1px solid var(--line);box-shadow:10px 10px 0 #b8cbc5}label{display:block;margin:18px 0 7px;font:700 12px Arial,sans-serif;letter-spacing:.08em;text-transform:uppercase}input,textarea{width:100%;padding:13px;border:1px solid var(--line);background:#fff;font:16px Georgia,serif}textarea{min-height:130px;resize:vertical}.error{padding:11px;background:#f9ded8;color:#8f2e1e}button{margin-top:24px;padding:14px 22px;border:0;background:var(--accent);color:#fff;font-weight:bold;cursor:pointer}
</style></head><body><main class="wrap"><a class="back" href="<?= e(site_url('products')) ?>">← Back to products</a><h1><?= e($heading) ?></h1><section class="panel"><?php if ($error): ?><p class="error"><?= e($error) ?></p><?php endif; ?><form method="post" action="<?= e($action) ?>"><label for="product_name">Product name</label><input id="product_name" name="product_name" maxlength="100" value="<?= e($product['product_name'] ?? '') ?>" required><label for="description">Description</label><textarea id="description" name="description"><?= e($product['description'] ?? '') ?></textarea><label for="price">Price</label><input id="price" name="price" type="number" min="0" step="0.01" value="<?= e($product['price'] ?? '') ?>" required><label for="quantity">Quantity</label><input id="quantity" name="quantity" type="number" min="0" step="1" value="<?= e($product['quantity'] ?? 0) ?>" required><button type="submit"><?= $is_edit ? 'Save changes' : 'Add product' ?></button></form></section></main></body></html>